#!/bin/bash

file=$1

if [ $# -eq 0 ]; then
	echo "No parameters passed."
elif [[ $file == *.java ]]; then
	echo 'Compiling Java File...'
	noExt=$(basename $file .java)
	path=$(dirname $file)
	javac $file 2>output.txt
	if [ -s output.txt ]; then
		cat output.txt
	else
		cd $path
		java $noExt
	fi
elif [[ $file == *.py ]]; then
	echo 'Running Python file...'
	python $file
else
	echo 'Not a recognized file type'
fi